//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources
import UIKit

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }
  var info: info { .init(bundle: bundle) }
  var font: font { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }
  var nib: nib { .init(bundle: bundle) }
  var storyboard: storyboard { .init(bundle: bundle) }

  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func info(bundle: Foundation.Bundle) -> info {
    .init(bundle: bundle)
  }
  func font(bundle: Foundation.Bundle) -> font {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func nib(bundle: Foundation.Bundle) -> nib {
    .init(bundle: bundle)
  }
  func storyboard(bundle: Foundation.Bundle) -> storyboard {
    .init(bundle: bundle)
  }
  func validate() throws {
    try self.font.validate()
    try self.nib.validate()
    try self.storyboard.validate()
  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.color` struct is generated, and contains static references to 3 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }

    /// Color `ColorBottonTabbar`.
    var colorBottonTabbar: RswiftResources.ColorResource { .init(name: "ColorBottonTabbar", path: [], bundle: bundle) }

    /// Color `TextColor`.
    var textColor: RswiftResources.ColorResource { .init(name: "TextColor", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 58 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `Arrow`.
    var arrow: RswiftResources.ImageResource { .init(name: "Arrow", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Close (1)`.
    var close1: RswiftResources.ImageResource { .init(name: "Close (1)", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Icon.button.left.1`.
    var iconButtonLeft1: RswiftResources.ImageResource { .init(name: "Icon.button.left.1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Icon.button.left.2`.
    var iconButtonLeft2: RswiftResources.ImageResource { .init(name: "Icon.button.left.2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Icon.button.left.3`.
    var iconButtonLeft3: RswiftResources.ImageResource { .init(name: "Icon.button.left.3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Icon.button.left.4`.
    var iconButtonLeft4: RswiftResources.ImageResource { .init(name: "Icon.button.left.4", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Volume`.
    var volume: RswiftResources.ImageResource { .init(name: "Volume", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `airplayIcon`.
    var airplayIcon: RswiftResources.ImageResource { .init(name: "airplayIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `arrowIntro`.
    var arrowIntro: RswiftResources.ImageResource { .init(name: "arrowIntro", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `bannerimage.1`.
    var bannerimage1: RswiftResources.ImageResource { .init(name: "bannerimage.1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `bannerimage.2`.
    var bannerimage2: RswiftResources.ImageResource { .init(name: "bannerimage.2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `bannerimage.setting`.
    var bannerimageSetting: RswiftResources.ImageResource { .init(name: "bannerimage.setting", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `chevronLeft`.
    var chevronLeft: RswiftResources.ImageResource { .init(name: "chevronLeft", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `chevronRight`.
    var chevronRight: RswiftResources.ImageResource { .init(name: "chevronRight", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `emptyIcon`.
    var emptyIcon: RswiftResources.ImageResource { .init(name: "emptyIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `emptyWeb`.
    var emptyWeb: RswiftResources.ImageResource { .init(name: "emptyWeb", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `facebookIcon`.
    var facebookIcon: RswiftResources.ImageResource { .init(name: "facebookIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `flipIcon`.
    var flipIcon: RswiftResources.ImageResource { .init(name: "flipIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `homeIcon`.
    var homeIcon: RswiftResources.ImageResource { .init(name: "homeIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iPhone 14 Pro 1`.
    var iPhone14Pro1: RswiftResources.ImageResource { .init(name: "iPhone 14 Pro 1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iPhone 14 Pro 2`.
    var iPhone14Pro2: RswiftResources.ImageResource { .init(name: "iPhone 14 Pro 2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iPhone 14 Pro 3`.
    var iPhone14Pro3: RswiftResources.ImageResource { .init(name: "iPhone 14 Pro 3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iPhone 14 Pro 4`.
    var iPhone14Pro4: RswiftResources.ImageResource { .init(name: "iPhone 14 Pro 4", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iPhone 14 Pro 5`.
    var iPhone14Pro5: RswiftResources.ImageResource { .init(name: "iPhone 14 Pro 5", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon.airplay`.
    var iconAirplay: RswiftResources.ImageResource { .init(name: "icon.airplay", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon.back.blue.button`.
    var iconBackBlueButton: RswiftResources.ImageResource { .init(name: "icon.back.blue.button", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon.back.button`.
    var iconBackButton: RswiftResources.ImageResource { .init(name: "icon.back.button", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon.back.playvideo`.
    var iconBackPlayvideo: RswiftResources.ImageResource { .init(name: "icon.back.playvideo", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon.button.ariplay`.
    var iconButtonAriplay: RswiftResources.ImageResource { .init(name: "icon.button.ariplay", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon.button.home`.
    var iconButtonHome: RswiftResources.ImageResource { .init(name: "icon.button.home", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon.button.home.setting`.
    var iconButtonHomeSetting: RswiftResources.ImageResource { .init(name: "icon.button.home.setting", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon.button.setting`.
    var iconButtonSetting: RswiftResources.ImageResource { .init(name: "icon.button.setting", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon.button.tutorial`.
    var iconButtonTutorial: RswiftResources.ImageResource { .init(name: "icon.button.tutorial", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon.check.button`.
    var iconCheckButton: RswiftResources.ImageResource { .init(name: "icon.check.button", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon.close.button`.
    var iconCloseButton: RswiftResources.ImageResource { .init(name: "icon.close.button", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon.home.back.button`.
    var iconHomeBackButton: RswiftResources.ImageResource { .init(name: "icon.home.back.button", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon.next.button`.
    var iconNextButton: RswiftResources.ImageResource { .init(name: "icon.next.button", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon.next.playvideo`.
    var iconNextPlayvideo: RswiftResources.ImageResource { .init(name: "icon.next.playvideo", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon.playvideo`.
    var iconPlayvideo: RswiftResources.ImageResource { .init(name: "icon.playvideo", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon.stopvideo`.
    var iconStopvideo: RswiftResources.ImageResource { .init(name: "icon.stopvideo", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `image.botton.browser`.
    var imageBottonBrowser: RswiftResources.ImageResource { .init(name: "image.botton.browser", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `image.botton.video`.
    var imageBottonVideo: RswiftResources.ImageResource { .init(name: "image.botton.video", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `image.button.photos`.
    var imageButtonPhotos: RswiftResources.ImageResource { .init(name: "image.button.photos", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `image.tvcap`.
    var imageTvcap: RswiftResources.ImageResource { .init(name: "image.tvcap", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `instagramIcon`.
    var instagramIcon: RswiftResources.ImageResource { .init(name: "instagramIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `intro1`.
    var intro1: RswiftResources.ImageResource { .init(name: "intro1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `intro2`.
    var intro2: RswiftResources.ImageResource { .init(name: "intro2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `intro3`.
    var intro3: RswiftResources.ImageResource { .init(name: "intro3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `mirrorScreeningIcon`.
    var mirrorScreeningIcon: RswiftResources.ImageResource { .init(name: "mirrorScreeningIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `netflixIcon`.
    var netflixIcon: RswiftResources.ImageResource { .init(name: "netflixIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `oval`.
    var oval: RswiftResources.ImageResource { .init(name: "oval", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `redirectIcon`.
    var redirectIcon: RswiftResources.ImageResource { .init(name: "redirectIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `rotate-left`.
    var rotateLeft: RswiftResources.ImageResource { .init(name: "rotate-left", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `rotateIcon`.
    var rotateIcon: RswiftResources.ImageResource { .init(name: "rotateIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `searchIcon`.
    var searchIcon: RswiftResources.ImageResource { .init(name: "searchIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `trashIcon`.
    var trashIcon: RswiftResources.ImageResource { .init(name: "trashIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `volume-high`.
    var volumeHigh: RswiftResources.ImageResource { .init(name: "volume-high", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `youtubeIcon`.
    var youtubeIcon: RswiftResources.ImageResource { .init(name: "youtubeIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    let bundle: Foundation.Bundle
    var uiApplicationSceneManifest: uiApplicationSceneManifest { .init(bundle: bundle) }

    func uiApplicationSceneManifest(bundle: Foundation.Bundle) -> uiApplicationSceneManifest {
      .init(bundle: bundle)
    }

    struct uiApplicationSceneManifest {
      let bundle: Foundation.Bundle

      let uiApplicationSupportsMultipleScenes: Bool = false

      var _key: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest"], key: "_key") ?? "UIApplicationSceneManifest" }
      var uiSceneConfigurations: uiSceneConfigurations { .init(bundle: bundle) }

      func uiSceneConfigurations(bundle: Foundation.Bundle) -> uiSceneConfigurations {
        .init(bundle: bundle)
      }

      struct uiSceneConfigurations {
        let bundle: Foundation.Bundle
        var _key: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations"], key: "_key") ?? "UISceneConfigurations" }
        var uiWindowSceneSessionRoleApplication: uiWindowSceneSessionRoleApplication { .init(bundle: bundle) }

        func uiWindowSceneSessionRoleApplication(bundle: Foundation.Bundle) -> uiWindowSceneSessionRoleApplication {
          .init(bundle: bundle)
        }

        struct uiWindowSceneSessionRoleApplication {
          let bundle: Foundation.Bundle
          var defaultConfiguration: defaultConfiguration { .init(bundle: bundle) }

          func defaultConfiguration(bundle: Foundation.Bundle) -> defaultConfiguration {
            .init(bundle: bundle)
          }

          struct defaultConfiguration {
            let bundle: Foundation.Bundle
            var uiSceneConfigurationName: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneConfigurationName") ?? "Default Configuration" }
            var uiSceneDelegateClassName: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneDelegateClassName") ?? "$(PRODUCT_MODULE_NAME).SceneDelegate" }
          }
        }
      }
    }
  }

  /// This `_R.font` struct is generated, and contains static references to 9 fonts.
  struct font: Sequence {
    let bundle: Foundation.Bundle

    /// Font `Inter-Black`.
    var interBlack: RswiftResources.FontResource { .init(name: "Inter-Black", bundle: bundle, filename: "Inter-Black.ttf") }

    /// Font `Inter-Bold`.
    var interBold: RswiftResources.FontResource { .init(name: "Inter-Bold", bundle: bundle, filename: "Inter-Bold.ttf") }

    /// Font `Inter-ExtraBold`.
    var interExtraBold: RswiftResources.FontResource { .init(name: "Inter-ExtraBold", bundle: bundle, filename: "Inter-ExtraBold.ttf") }

    /// Font `Inter-ExtraLight`.
    var interExtraLight: RswiftResources.FontResource { .init(name: "Inter-ExtraLight", bundle: bundle, filename: "Inter-ExtraLight.ttf") }

    /// Font `Inter-Light`.
    var interLight: RswiftResources.FontResource { .init(name: "Inter-Light", bundle: bundle, filename: "Inter-Light.ttf") }

    /// Font `Inter-Medium`.
    var interMedium: RswiftResources.FontResource { .init(name: "Inter-Medium", bundle: bundle, filename: "Inter-Medium.ttf") }

    /// Font `Inter-Regular`.
    var interRegular: RswiftResources.FontResource { .init(name: "Inter-Regular", bundle: bundle, filename: "Inter-Regular.ttf") }

    /// Font `Inter-SemiBold`.
    var interSemiBold: RswiftResources.FontResource { .init(name: "Inter-SemiBold", bundle: bundle, filename: "Inter-SemiBold.ttf") }

    /// Font `Inter-Thin`.
    var interThin: RswiftResources.FontResource { .init(name: "Inter-Thin", bundle: bundle, filename: "Inter-Thin.ttf") }

    func makeIterator() -> IndexingIterator<[RswiftResources.FontResource]> {
      [interBlack, interBold, interExtraBold, interExtraLight, interLight, interMedium, interRegular, interSemiBold, interThin].makeIterator()
    }
    func validate() throws {
      for font in self {
        if !font.canBeLoaded() { throw RswiftResources.ValidationError("[R.swift] Font '\(font.name)' could not be loaded, is '\(font.filename)' added to the UIAppFonts array in this targets Info.plist?") }
      }
    }
  }

  /// This `_R.file` struct is generated, and contains static references to 9 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `Inter-Black.ttf`.
    var interBlackTtf: RswiftResources.FileResource { .init(name: "Inter-Black", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Inter-Bold.ttf`.
    var interBoldTtf: RswiftResources.FileResource { .init(name: "Inter-Bold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Inter-ExtraBold.ttf`.
    var interExtraBoldTtf: RswiftResources.FileResource { .init(name: "Inter-ExtraBold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Inter-ExtraLight.ttf`.
    var interExtraLightTtf: RswiftResources.FileResource { .init(name: "Inter-ExtraLight", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Inter-Light.ttf`.
    var interLightTtf: RswiftResources.FileResource { .init(name: "Inter-Light", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Inter-Medium.ttf`.
    var interMediumTtf: RswiftResources.FileResource { .init(name: "Inter-Medium", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Inter-Regular.ttf`.
    var interRegularTtf: RswiftResources.FileResource { .init(name: "Inter-Regular", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Inter-SemiBold.ttf`.
    var interSemiBoldTtf: RswiftResources.FileResource { .init(name: "Inter-SemiBold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Inter-Thin.ttf`.
    var interThinTtf: RswiftResources.FileResource { .init(name: "Inter-Thin", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }
  }

  /// This `_R.nib` struct is generated, and contains static references to 27 nibs.
  struct nib {
    let bundle: Foundation.Bundle

    /// Nib `AlbumsCollectionViewCell`.
    var albumsCollectionViewCell: RswiftResources.NibReference<AlbumsCollectionViewCell> { .init(name: "AlbumsCollectionViewCell", bundle: bundle) }

    /// Nib `AlbumsViewController`.
    var albumsViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "AlbumsViewController", bundle: bundle) }

    /// Nib `BrowserTableViewCell`.
    var browserTableViewCell: RswiftResources.NibReference<BrowserTableViewCell> { .init(name: "BrowserTableViewCell", bundle: bundle) }

    /// Nib `BrowserViewController`.
    var browserViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "BrowserViewController", bundle: bundle) }

    /// Nib `ConnectViewController`.
    var connectViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "ConnectViewController", bundle: bundle) }

    /// Nib `EmptyLibraryView`.
    var emptyLibraryView: RswiftResources.NibReference<UIKit.UIView> { .init(name: "EmptyLibraryView", bundle: bundle) }

    /// Nib `ErrorMirroringViewController`.
    var errorMirroringViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "ErrorMirroringViewController", bundle: bundle) }

    /// Nib `HistorySearchTableViewCell`.
    var historySearchTableViewCell: RswiftResources.NibReference<HistorySearchTableViewCell> { .init(name: "HistorySearchTableViewCell", bundle: bundle) }

    /// Nib `HomeViewController`.
    var homeViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "HomeViewController", bundle: bundle) }

    /// Nib `IntroCollectionViewCell`.
    var introCollectionViewCell: RswiftResources.NibReference<IntroCollectionViewCell> { .init(name: "IntroCollectionViewCell", bundle: bundle) }

    /// Nib `IntroViewController`.
    var introViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "IntroViewController", bundle: bundle) }

    /// Nib `MirroringStopViewController`.
    var mirroringStopViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "MirroringStopViewController", bundle: bundle) }

    /// Nib `MirroringTutorialViewController`.
    var mirroringTutorialViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "MirroringTutorialViewController", bundle: bundle) }

    /// Nib `ModalBottomView`.
    var modalBottomView: RswiftResources.NibReference<UIKit.UIView> { .init(name: "ModalBottomView", bundle: bundle) }

    /// Nib `MoreRecentsViewController`.
    var moreRecentsViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "MoreRecentsViewController", bundle: bundle) }

    /// Nib `PhotoCastViewController`.
    var photoCastViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "PhotoCastViewController", bundle: bundle) }

    /// Nib `PhotoCollectionViewCell`.
    var photoCollectionViewCell: RswiftResources.NibReference<PhotoCollectionViewCell> { .init(name: "PhotoCollectionViewCell", bundle: bundle) }

    /// Nib `PhotoViewController`.
    var photoViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "PhotoViewController", bundle: bundle) }

    /// Nib `SelectDeviceViewController`.
    var selectDeviceViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "SelectDeviceViewController", bundle: bundle) }

    /// Nib `SettingViewController`.
    var settingViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "SettingViewController", bundle: bundle) }

    /// Nib `SocialCollectionViewCell`.
    var socialCollectionViewCell: RswiftResources.NibReference<SocialCollectionViewCell> { .init(name: "SocialCollectionViewCell", bundle: bundle) }

    /// Nib `TutorialView`.
    var tutorialView: RswiftResources.NibReference<UIKit.UIView> { .init(name: "TutorialView", bundle: bundle) }

    /// Nib `TutorialViewController`.
    var tutorialViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "TutorialViewController", bundle: bundle) }

    /// Nib `TutorialWithStepViewController`.
    var tutorialWithStepViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "TutorialWithStepViewController", bundle: bundle) }

    /// Nib `VideoLibraryCollectionViewCell`.
    var videoLibraryCollectionViewCell: RswiftResources.NibReference<VideoLibraryCollectionViewCell> { .init(name: "VideoLibraryCollectionViewCell", bundle: bundle) }

    /// Nib `VideoLibraryViewController`.
    var videoLibraryViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "VideoLibraryViewController", bundle: bundle) }

    /// Nib `VideoPlayerViewController`.
    var videoPlayerViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "VideoPlayerViewController", bundle: bundle) }

    func validate() throws {
      if UIKit.UIImage(named: "instagramIcon", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'instagramIcon' is used in nib 'BrowserTableViewCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "chevronLeft", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'chevronLeft' is used in nib 'BrowserViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "chevronRight", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'chevronRight' is used in nib 'BrowserViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "emptyWeb", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'emptyWeb' is used in nib 'BrowserViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "homeIcon", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'homeIcon' is used in nib 'BrowserViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "rotate-left", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'rotate-left' is used in nib 'BrowserViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "icon.airplay", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'icon.airplay' is used in nib 'ConnectViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "TextColor", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'TextColor' is used in nib 'ConnectViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "emptyIcon", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'emptyIcon' is used in nib 'EmptyLibraryView', but couldn't be loaded.") }
      if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "plus") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'plus' is used in nib 'EmptyLibraryView', but couldn't be loaded.") } }
      if UIKit.UIImage(named: "icon.airplay", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'icon.airplay' is used in nib 'ErrorMirroringViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "TextColor", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'TextColor' is used in nib 'ErrorMirroringViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "redirectIcon", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'redirectIcon' is used in nib 'HistorySearchTableViewCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "searchIcon", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'searchIcon' is used in nib 'HistorySearchTableViewCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "icon.button.ariplay", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'icon.button.ariplay' is used in nib 'HomeViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "icon.button.home", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'icon.button.home' is used in nib 'HomeViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "icon.button.home.setting", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'icon.button.home.setting' is used in nib 'HomeViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "icon.button.tutorial", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'icon.button.tutorial' is used in nib 'HomeViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "icon.home.back.button", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'icon.home.back.button' is used in nib 'HomeViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "image.botton.browser", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'image.botton.browser' is used in nib 'HomeViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "image.botton.video", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'image.botton.video' is used in nib 'HomeViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "image.button.photos", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'image.button.photos' is used in nib 'HomeViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "image.tvcap", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'image.tvcap' is used in nib 'HomeViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "TextColor", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'TextColor' is used in nib 'HomeViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "intro1", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'intro1' is used in nib 'IntroCollectionViewCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "arrowIntro", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'arrowIntro' is used in nib 'IntroViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "bannerimage.2", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'bannerimage.2' is used in nib 'MirroringStopViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "TextColor", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'TextColor' is used in nib 'MirroringStopViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "bannerimage.1", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'bannerimage.1' is used in nib 'MirroringTutorialViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "TextColor", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'TextColor' is used in nib 'MirroringTutorialViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "airplayIcon", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'airplayIcon' is used in nib 'SelectDeviceViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "Icon.button.left.1", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'Icon.button.left.1' is used in nib 'SettingViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "Icon.button.left.2", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'Icon.button.left.2' is used in nib 'SettingViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "Icon.button.left.3", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'Icon.button.left.3' is used in nib 'SettingViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "Icon.button.left.4", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'Icon.button.left.4' is used in nib 'SettingViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "bannerimage.setting", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'bannerimage.setting' is used in nib 'SettingViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "icon.back.blue.button", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'icon.back.blue.button' is used in nib 'SettingViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "icon.button.setting", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'icon.button.setting' is used in nib 'SettingViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "icon.next.button", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'icon.next.button' is used in nib 'SettingViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "instagramIcon", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'instagramIcon' is used in nib 'SocialCollectionViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "TextColor", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'TextColor' is used in nib 'TutorialView', but couldn't be loaded.") }
      if UIKit.UIImage(named: "Arrow", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'Arrow' is used in nib 'TutorialViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "icon.next.button", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'icon.next.button' is used in nib 'TutorialViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "TextColor", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'TextColor' is used in nib 'TutorialViewController', but couldn't be loaded.") }
      if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "1.circle.fill") == nil { throw RswiftResources.ValidationError("[R.swift] System image named '1.circle.fill' is used in nib 'TutorialWithStepViewController', but couldn't be loaded.") } }
      if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "2.circle.fill") == nil { throw RswiftResources.ValidationError("[R.swift] System image named '2.circle.fill' is used in nib 'TutorialWithStepViewController', but couldn't be loaded.") } }
      if UIKit.UIImage(named: "mirrorScreeningIcon", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'mirrorScreeningIcon' is used in nib 'TutorialWithStepViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "icon.back.blue.button", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'icon.back.blue.button' is used in nib 'VideoLibraryViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "AccentColor", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'AccentColor' is used in nib 'VideoLibraryViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "TextColor", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'TextColor' is used in nib 'VideoLibraryViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "Close (1)", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'Close (1)' is used in nib 'VideoPlayerViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "Volume", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'Volume' is used in nib 'VideoPlayerViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "volume-high", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'volume-high' is used in nib 'VideoPlayerViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "TextColor", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'TextColor' is used in nib 'VideoPlayerViewController', but couldn't be loaded.") }
    }
  }

  /// This `_R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    let bundle: Foundation.Bundle
    var launchScreen: launchScreen { .init(bundle: bundle) }

    func launchScreen(bundle: Foundation.Bundle) -> launchScreen {
      .init(bundle: bundle)
    }
    func validate() throws {
      try self.launchScreen.validate()
    }


    /// Storyboard `LaunchScreen`.
    struct launchScreen: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = UIKit.UIViewController

      let bundle: Foundation.Bundle

      let name = "LaunchScreen"
      func validate() throws {

      }
    }
  }
}